// Generated by Assets/Hananoki/SymbolSettings/Editor/Localize/ja-JP.csv
namespace Hananoki.SymbolSettings {
	public static class L {
		public static string Tr( string s ) {
			return EditorLocalize.Tr( EditorLocalize.GetPakage( Package.name ), s );
		}
		public static string[] Tr( string[] ss ) {
			return EditorLocalize.Tr( EditorLocalize.GetPakage( Package.name ), ss );
		}
	}
	public static class S {
		public static string _EditSettings => L.Tr( "Edit Settings" );
		public static string _ActiveBuildTarget => L.Tr( "ActiveBuildTarget" );
		public static string _PreviewScriptingDefineSymbols => L.Tr( "Preview ScriptingDefineSymbols" );
		public static string _Project_ScriptingDefineSymbols_ => L.Tr( "Project \"ScriptingDefineSymbols\"" );
		public static string _EditorShared_ScriptingDefineSymbols_ => L.Tr( "Editor Shared \"ScriptingDefineSymbols\"" );
		public static string _BuildOnly_ScriptingDefineSymbols_ => L.Tr( "BuildOnly \"ScriptingDefineSymbols\"" );
		public static string _EnablePlatform => L.Tr( "Enable Platform" );
		public static string _ShowBuilt_inSymbols => L.Tr( "Show Built-in Symbols" );
		public static string _Nothingcanbespecifiedforthecurrentbuildtarget => L.Tr( "Nothing can be specified for the current build target" );
	}
}
